import turtle

uno = turtle.Turtle()

one = 0
 
while one < 90:
	uno.stamp()
	uno.forward(10)
	uno.left(108)
	uno.forward(7)
	uno.back(7)
	uno.right(108)
	uno.right(108)
	uno.forward(7)
	uno.back(7)
	uno.left(108)
	uno.forward(108)
	uno.stamp()
	uno.penup()
	uno.forward(100)
	uno.right(90)
	uno.forward(70)
	uno.left(90)
	uno.pendown()
	uno.color("purple")
	uno.circle(60)
	uno.pu()
	uno.left(90)
	uno.forward(10)
	uno.pd()
	uno.right(90)
	uno.color("blue")
	uno.circle(50)
	uno.pu()
	uno.left(90)
	uno.forward(10)
	uno.pd()
	uno.right(90)
	uno.color("pink")
	uno.circle(40)
	uno.pu()
        uno.left(90)
        uno.forward(10)
        uno.pd()
        uno.right(90)
        uno.color("green")
        uno.circle(30)
	uno.pu()
        uno.left(90)
        uno.forward(10)
        uno.pd()
        uno.right(90)
        uno.color("yellow")
        uno.circle(20)
	uno.pu()
        uno.left(90)
        uno.forward(10)
        uno.pd()
        uno.right(90)
        uno.color("red")
        uno.circle(10)
	uno.pu()
	uno.left(90)
	uno.forward(5)
	uno.pd()
	uno.shape("turtle")
	one = one + 1
	turtle.exitonclick()
